try {
  console.log("try 블록 시작")
  lalala;
  console.log("try 블록 끝")
} catch (err) {
  console.log("이걸 본다는 것은 코드가 뭔가 문제가 있다.")
}
